### ISSUE TITLE
Punctuations missing in downloaded cvs

### ISSUE THREAD

**Issue by Sadam1195** [thehetpandya/youtube_tts_data_generator#1]
Hi Pandya, thanks for creating great resource. Everything works great apart from the fact that this package removes punctuation in the subtitles which I suppose you could understand is very bad things for training as without punctuations attention model will fail to converge hence bad output. Do you know any fix for that?

I am generating dataset for a Spanish video with `lang='es'`

@hetpandya

**Comment by hetpandya** [comment]
Hi @Sadam1195 , thanks a lot for the appreciation. 
Thank you for pointing out the issue. I do understand the importance of punctuations while building speech synthesis algorithms. 
>> Everything works great apart from the fact that this package removes punctuation in the subtitles which I suppose you could understand is very bad things for training as without punctuations attention model will fail to converge hence bad output. Do you know any fix for that?

This happens because my package uses [youtube-dl](https://github.com/ytdl-org/youtube-dl) to download subtitles and somehow youtube-dl skips the punctuations while downloading them although they seem to be present in the video's captions. Sadly the dependency doesn't seem to mention anything about punctuations. I shall look upon adding a feature to my library to automatically punctuate the captions soon using deep learning. Meanwhile I have found a repo if that could help you https://github.com/chrisspen/punctuator2 . This seems to be trained only on english data though. Let me know if I can help you.

**Comment by Sadam1195** [comment]
> Hi @Sadam1195 , thanks a lot for the appreciation.
> Thank you for pointing out the issue. I do understand the importance of punctuations while building speech synthesis algorithms.
> 
> > > Everything works great apart from the fact that this package removes punctuation in the subtitles which I suppose you could understand is very bad things for training as without punctuations attention model will fail to converge hence bad output. Do you know any fix for that?
> 
> This happens because my package uses [youtube-dl](https://github.com/ytdl-org/youtube-dl) to download subtitles and somehow youtube-dl skips the punctuations while downloading them although they seem to be present in the video's captions. Sadly the dependency doesn't seem to mention anything about punctuations. I shall look upon adding a feature to my library to automatically punctuate the captions soon using deep learning. Meanwhile I have found a repo if that could help you https://github.com/chrisspen/punctuator2 . This seems to be trained only on english data though. Let me know if I can help you.

I have fixed the punctuation issue with additional code. I will add a PR later and maybe you can merge it.

**Comment by hetpandya** [comment]
Sure, suggestions are welcome.
